version: "3"
services:
  backend:
    build:
      context: ./backend/
    command: /app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"