version: "3.8"

services:
  backend:
    build:
      context: ./backend/
    command: npm start
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    links:
      - "backend:be"