# client

FROM node:16-alpine as frontend

WORKDIR /app/frontend/
COPY frontend/package*.json .
RUN npm i
COPY ./frontend .
RUN npm run build


# server

FROM node:16-alpine as backend

WORKDIR /app/backend/
COPY --from=frontend /app/frontend/build/ ./frontend/build/

WORKDIR /app/server/
COPY ./backend/package*.json .
RUN npm i
COPY ./backend ./

ENV PORT 8000

EXPOSE 8000

CMD ["npm", "start"]